* no longer installer XDG and debian menu entries, configure-networkcard is   being deprectaed in favour of Ceni. * switch from custom su-me to generic su-to-root, adapt dependencies and   menu files accordingly. * move desktop file into standard XDG hierarchy.

diff --git a/sidux-networkconfig b/sidux-networkconfig
--- a/sidux-networkconfig
+++ b/sidux-networkconfig
@@ -57,11 +57,9 @@ if [ -n "$1" ]; then
 fi
 
 # Test if root:
-SU_ME=$(type -p su-me)  || SU_ME="/usr/bin/su-me"
-if [ "$UID" -ne 0 ]; then
-	[ -x "$SU_ME" ] && exec "$SU_ME" "$0" 
-	
-	echo "Error: You must be root to run this script!"
+if [ "$(id -u)" -ne 0 ]; then
+	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
+	printf "ERROR: $0 needs root capabilities, please start it as root.\n\n" >&2
 	exit 1
 fi
 
